# joint_recovery.R -- CAN THE FIT RECOVER A KNOWN TRUTH? and the uncertainty machinery it needs.
#
# Architecture, and why it is built this way.
#
# The generative model and the fitted model are THE SAME CODE. Expected counts come from
# jm_fitted_cpp, the identical C++ that the likelihood uses, and the only thing added is the
# negative-binomial draw. So there is no second simulator that can drift away from the model, which is
# the usual way a recovery test ends up testing nothing.
#
# Truth is simulated onto the REAL DESIGN: the same countries, seasons, observed weeks, missing cells,
# populations, contact matrices, vaccination coverages and data sources as the actual panel. The
# question is therefore not "can this model be recovered from ideal data" but "can it be recovered
# from the data we actually have", which is the only question worth asking.
#
# Truth itself comes from a pluggable constructor, and that is the hook for the learning layer:
#   jm_truth_from_fit()    truth = the fitted optimum, optionally jittered. Asks whether the optimum
#                          is locally recoverable and whether the intervals cover.
#   jm_truth_from_prior()  truth drawn from the priors. Asks whether recovery holds across the whole
#                          plausible parameter space, not just near one point.
#   jm_truth_with_driver() truth in which the season parameters are GENERATED BY A DRIVER
#                          (subtype, vaccine effectiveness, prior-season burden). This is the
#                          learning layer's own recovery test: simulate a world where a driver really
#                          does move season transmissibility or season visibility by a known amount,
#                          run the whole two-step pipeline, and check the driver effect comes back.
#                          Without this, a driver association found in real data cannot be told apart
#                          from one manufactured by the fitting procedure.
#
# Everything returns tidy truth-versus-estimate tables, so bias, root-mean-square error, rank
# recovery and interval coverage are all computed the same way whatever the truth constructor was.

suppressMessages({library(dplyr); library(tidyr)})

# ---- |-uncertainty: curvature intervals for every parameter ----
# The penalised Hessian at the optimum gives a Gaussian approximation to the posterior on the
# unconstrained scale. Intervals are formed there and then pushed through the parameter's own
# transform, which is exact for quantiles because every transform used here is monotone.
jm_intervals = function(fit, H_post = NULL, level = 0.95){
  d = fit$d; th = fit$theta; nm = names(th)
  if (is.null(H_post)) H_post = optimHess(th, function(x) jm_negll_cpp(x, d))
  H_post = (H_post + t(H_post)) / 2
  V = tryCatch(solve(H_post), error = function(e) NULL)
  se = if (is.null(V)) rep(NA_real_, length(th)) else sqrt(pmax(diag(V), 0))
  z = qnorm(1 - (1 - level) / 2)
  lo_u = th - z * se; hi_u = th + z * se
  # the transform each slot lives behind, and a human-readable name
  kind = ifelse(grepl("^log_R0", nm), "exp",
         ifelse(grepl("^delta_", nm), "identity",
         ifelse(grepl("^log2_sigma", nm), "pow2",
         ifelse(grepl(":logit_S0", nm), "plogis",
         ifelse(grepl(":off_", nm), "pow2", "exp")))))
  tr = function(x, k) ifelse(k == "exp", exp(x), ifelse(k == "plogis", plogis(x),
                      ifelse(k == "pow2", 2^x, x)))
  out = data.frame(parameter = nm, kind = kind, theta = unname(th), se = unname(se),
             estimate = tr(unname(th), kind), lower = tr(unname(lo_u), kind), upper = tr(unname(hi_u), kind),
             row.names = NULL, stringsAsFactors = FALSE)
  # The LAST season deviation is not a free parameter: it is minus the sum of the others, so the
  # sum-to-zero constraint holds. Its interval needs the delta method, i.e. the variance of that sum,
  # which is the total of the whole covariance sub-block rather than a single diagonal entry.
  S = d$n_season; jf = S + seq_len(S - 1)
  if (!is.null(V)){
    se_last = sqrt(max(sum(V[jf, jf, drop = FALSE]), 0))
    th_last = -sum(th[jf])
    out = rbind(out, data.frame(parameter = paste0("delta_", d$seasons[S]), kind = "identity",
                                theta = th_last, se = se_last, estimate = th_last,
                                lower = th_last - z * se_last, upper = th_last + z * se_last,
                                row.names = NULL, stringsAsFactors = FALSE))
  }
  out
}

# ---- |-uncertainty: profile likelihood for the shared parameters ----
# Curvature intervals assume the objective is a quadratic bowl. Near a flat or banana-shaped valley
# that is exactly what fails, and flat valleys are what this project keeps finding. A profile makes
# no such assumption: fix one parameter on a grid, re-optimise everything else, and read off where the
# objective has risen by qchisq(.95, 1)/2 = 1.92. Only the shared parameters get this treatment --
# they are the ones that will be published, and they are few.
jm_profile = function(fit, idx = NULL, n_grid = 7L, span = 3, sweeps = 2L,
                      cores = max(1L, parallel::detectCores() - 1L), verbose = TRUE){
  d = fit$d; th0 = fit$theta; nm = names(th0)
  if (is.null(idx)) idx = seq_len(2L * d$n_season)              # the shared block by default
  iv = jm_intervals(fit)
  best = fit$negll
  cut = qchisq(0.95, 1) / 2
  bl = jm_blocks(d)
  one = function(j){
    se = iv$se[j]; if (!is.finite(se) || se <= 0) se = 0.1
    grid = th0[j] + seq(-span, span, length.out = n_grid) * se
    vals = vapply(grid, function(g){
      th = th0; th[j] = g
      for (sw in seq_len(sweeps)){
        # every local block, with the shared block (including the fixed j) held
        for (ic in seq_len(d$n_country)){
          ii = bl$local[[ic]]
          f = function(x){ t2 = th; t2[ii] = x; jm_country_negll_cpp(t2, d, ic - 1L) }
          o = tryCatch(optim(th[ii], f, method = "BFGS", control = list(maxit = 200, reltol = 1e-9)),
                       error = function(e) NULL)
          if (!is.null(o)) th[ii] = o$par
        }
        # the rest of the shared block, with j still fixed
        ii = setdiff(bl$shared, j)
        f = function(x){ t2 = th; t2[ii] = x; jm_negll_cpp(t2, d) }
        o = tryCatch(optim(th[ii], f, method = "BFGS", control = list(maxit = 200, reltol = 1e-9)),
                     error = function(e) NULL)
        if (!is.null(o)) th[ii] = o$par
      }
      jm_negll_cpp(th, d)
    }, numeric(1))
    data.frame(parameter = nm[j], j = j, theta = grid, negll = vals, delta = vals - best,
               row.names = NULL, stringsAsFactors = FALSE)
  }
  if (verbose) cat(sprintf("profiling %d parameters on %d grid points...\n", length(idx), n_grid))
  prof = do.call(rbind, parallel::mclapply(idx, one, mc.cores = min(cores, length(idx))))
  # read the interval off each profile by linear interpolation on the two sides of the minimum
  lim = do.call(rbind, lapply(split(prof, prof$parameter), function(p){
    p = p[order(p$theta), ]; imin = which.min(p$delta)
    side = function(seq_i){
      s = p[seq_i, ]; if (nrow(s) < 2) return(NA_real_)
      k = which(s$delta >= cut)[1]
      if (is.na(k) || k == 1) return(NA_real_)
      x1 = s$theta[k - 1]; x2 = s$theta[k]; y1 = s$delta[k - 1]; y2 = s$delta[k]
      x1 + (cut - y1) * (x2 - x1) / (y2 - y1)
    }
    data.frame(parameter = p$parameter[1], j = p$j[1],
               lo_theta = side(rev(seq_len(imin))), hi_theta = side(seq(imin, nrow(p))),
               row.names = NULL, stringsAsFactors = FALSE)
  }))
  lim$kind = iv$kind[lim$j]
  tr = function(x, k) ifelse(k == "exp", exp(x), ifelse(k == "plogis", plogis(x), ifelse(k == "pow2", 2^x, x)))
  lim$estimate = tr(th0[lim$j], lim$kind)
  lim$lower = tr(lim$lo_theta, lim$kind); lim$upper = tr(lim$hi_theta, lim$kind)
  list(profile = prof, limits = lim, cut = cut)
}

# ============================ the recovery harness ============================

# ---- |-truth constructors. Each returns a full parameter vector on the model's own scale. ----
jm_truth_from_fit = function(fit, jitter_sd = 0){
  th = fit$theta
  if (jitter_sd > 0) th = th + rnorm(length(th), 0, jitter_sd)
  th
}
jm_truth_from_prior = function(d, set = jm_settings(), anchor = NULL){
  # draw from the priors, but keep the seeds near the data-driven start: a seed drawn from its very
  # wide prior would put the wave outside the observation window and test nothing.
  th = if (is.null(anchor)) jm_theta0(d, set) else anchor
  S = d$n_season
  th[seq_len(S)] = rnorm(S, set$pr_R0_mean, set$pr_R0_sd)
  dev = rnorm(S, 0, set$pr_delta_sd); dev = dev - mean(dev)          # respect the sum-to-zero constraint
  th[S + seq_len(S - 1)] = dev[seq_len(S - 1)]
  th[2L * S] = rnorm(1, set$pr_sigma_mean, set$pr_sigma_sd)
  for (ic in seq_len(d$n_country)){
    b = d$off_country[ic]
    th[b + 1] = rnorm(1, set$pr_S0_mean, set$pr_S0_sd)
    th[b + 2] = th[b + 2] + rnorm(1, 0, 0.3)                          # around the data-driven level
    th[b + 3] = rnorm(1, 0, set$pr_off_sd); th[b + 4] = rnorm(1, 0, set$pr_off_sd)
    th[b + 5] = rnorm(1, set$pr_phi_mean, 0.4)
    th[b + 5 + seq_len(d$n_src[ic])] = th[b + 5 + seq_len(d$n_src[ic])] + rnorm(d$n_src[ic], 0, 0.3)
    is = b + 5 + d$n_src[ic] + seq_len(d$n_cs_of_country[ic])
    th[is] = th[is] + rnorm(length(is), 0, 0.5)                       # jitter the arrival, do not redraw it
  }
  names(th) = jm_par_names(d); th
}
# THE LEARNING-LAYER HOOK. x is one covariate value per season (subtype, vaccine effectiveness,
# prior-season burden, ...). The truth is built so that the covariate REALLY DOES move the season
# parameter by a known amount, on the model's own scale:
#   log R0_s     = pr_R0_mean   + beta_R0  * x_s + noise
#   delta_s      = beta_delta * x_s + noise, then centred to average zero
# Running the pipeline on this and regressing the FITTED season parameters back on x recovers
# beta_R0 and beta_delta if and only if the two-step procedure is trustworthy.
jm_truth_with_driver = function(d, x, beta_R0 = 0, beta_delta = 0, set = jm_settings(),
                                noise_R0 = 0.03, noise_delta = 0.15, anchor = NULL){
  stopifnot(length(x) == d$n_season)
  th = if (is.null(anchor)) jm_theta0(d, set) else anchor
  S = d$n_season; xs = as.numeric(scale(x))
  th[seq_len(S)] = set$pr_R0_mean + beta_R0 * xs + rnorm(S, 0, noise_R0)
  dev = beta_delta * xs + rnorm(S, 0, noise_delta); dev = dev - mean(dev)
  th[S + seq_len(S - 1)] = dev[seq_len(S - 1)]
  names(th) = jm_par_names(d)
  attr(th, "driver") = list(x = xs, beta_R0 = beta_R0, beta_delta = beta_delta)
  th
}

# ---- |-simulate one data set from a truth, onto the real design ----
# The expected counts come from the same C++ used by the likelihood; only the negative-binomial draw
# is added. The missing-cell pattern of the real panel is preserved, and the derived fields the
# starting values are built from are recomputed, so the refit starts from the SIMULATED data and gets
# no help from the real series.
jm_simulate = function(theta, d, seed = NULL){
  if (!is.null(seed)) set.seed(seed)
  p = jm_unpack(theta, d); f = jm_fitted_cpp(theta, d)
  ds = d
  for (i in seq_len(d$n_cs)){
    ic = d$cs_country[i] + 1L; phi = p$country[[ic]]$phi
    mu = f$mu[[i]]; ok = is.finite(d$y[[i]])
    ysim = matrix(NA_real_, nrow(mu), ncol(mu))
    ysim[ok] = rnbinom(sum(ok), size = phi, mu = mu[ok])
    dimnames(ysim) = dimnames(d$y[[i]])                              # keep the real design's labels
    ds$y[[i]] = ysim
    ds$lgamma_y1[i] = sum(lgamma(ysim[is.finite(ysim)] + 1))
    ds$rates[[i]] = sweep(ysim, 2, d$rate_per / d$N[[ic]], "*")       # the start is built from these
  }
  ds
}

# ---- |-one replicate: simulate, refit from scratch, compare with the truth ----
jm_recover_once = function(d, theta_true, seed, fit_args = list(), with_intervals = TRUE, verbose = FALSE){
  ds = jm_simulate(theta_true, d, seed)
  fit = do.call(jm_fit, c(list(d = ds, theta0 = jm_theta0(ds), verbose = verbose), fit_args))
  iv = if (with_intervals) jm_intervals(fit) else NULL
  nm = jm_par_names(d)
  # compare on the model's own scale (exp / logis / 2^), which is what gets reported
  kind = if (!is.null(iv)) iv$kind else jm_intervals(fit)$kind
  tr = function(x, k) ifelse(k == "exp", exp(x), ifelse(k == "plogis", plogis(x), ifelse(k == "pow2", 2^x, x)))
  out = data.frame(parameter = nm, seed = seed,
                   truth_theta = unname(theta_true), est_theta = unname(fit$theta),
                   truth = tr(unname(theta_true), kind), estimate = tr(unname(fit$theta), kind),
                   row.names = NULL, stringsAsFactors = FALSE)
  if (!is.null(iv)){ out$lower = iv$lower; out$upper = iv$upper
    out$covered = out$truth >= pmin(iv$lower, iv$upper) & out$truth <= pmax(iv$lower, iv$upper) }
  list(comparison = out, negll = fit$negll, loglik = fit$loglik, seconds = fit$seconds,
       conv = c(fit$conv_local, fit$conv_shared, fit$conv_polish), theta = fit$theta)
}

# ---- |-many replicates ----
# Replicates run SEQUENTIALLY because each fit already parallelises over countries; nesting the two
# would oversubscribe the cores and be slower, not faster.
jm_recovery = function(d, truth_fn = function(i) jm_truth_from_fit(fit0), n_rep = 10L, seed0 = 1000L,
                       fit_args = list(), verbose = TRUE){
  reps = vector("list", n_rep); t0 = Sys.time()
  for (i in seq_len(n_rep)){
    set.seed(seed0 + i)
    tt = truth_fn(i)
    r = tryCatch(jm_recover_once(d, tt, seed0 + i, fit_args), error = function(e){ cat("  rep", i, "FAILED:", conditionMessage(e), "\n"); NULL })
    if (!is.null(r)){ r$comparison$rep = i; r$driver = attr(tt, "driver"); reps[[i]] = r }
    if (verbose) cat(sprintf("  rep %2d/%d: negll %.1f, %.0f s (elapsed %.1f min)\n", i, n_rep,
                             if (is.null(r)) NA else r$negll, if (is.null(r)) NA else r$seconds,
                             as.numeric(difftime(Sys.time(), t0, units = "mins"))))
  }
  reps = Filter(Negate(is.null), reps)
  list(reps = reps, comparison = do.call(rbind, lapply(reps, `[[`, "comparison")),
       minutes = as.numeric(difftime(Sys.time(), t0, units = "mins")))
}

# ---- |-what the replicates say: bias, error, rank recovery, coverage ----
jm_recovery_summary = function(rec, d){
  cmp = rec$comparison
  fam = function(nm) ifelse(grepl("^log_R0", nm), "R0 (season, shared)",
        ifelse(grepl("^delta_", nm), "season deviation (shared)",
        ifelse(grepl("^log2_sigma", nm), "elderly susceptibility (global)",
        ifelse(grepl(":logit_S0", nm), "S0 (country)",
        ifelse(grepl(":log_c$", nm), "reporting c (country)",
        ifelse(grepl(":off_", nm), "age reporting offset",
        ifelse(grepl(":log_phi", nm), "dispersion phi",
        ifelse(grepl(":log_b_", nm), "baseline b", "seed I0 (country-season)"))))))))
  cmp$family = fam(cmp$parameter)
  by_fam = cmp %>% group_by(family) %>%
    summarise(n = n(),
              bias_theta = mean(est_theta - truth_theta),
              rmse_theta = sqrt(mean((est_theta - truth_theta)^2)),
              rel_bias = mean((estimate - truth) / abs(truth)),
              coverage = if ("covered" %in% names(cmp)) mean(covered, na.rm = TRUE) else NA_real_,
              .groups = "drop") %>% arrange(family)
  # rank recovery: within each replicate, does the ORDER of the shared season parameters come back?
  rank_rec = cmp %>% filter(grepl("^log_R0|^delta_", parameter)) %>%
    mutate(block = ifelse(grepl("^log_R0", parameter), "R0 by season", "season deviation")) %>%
    group_by(rep, block) %>%
    summarise(spearman = suppressWarnings(cor(truth, estimate, method = "spearman")),
              pearson = cor(truth, estimate), .groups = "drop") %>%
    group_by(block) %>% summarise(spearman_med = median(spearman, na.rm = TRUE),
                                  pearson_med = median(pearson, na.rm = TRUE), n_rep = n(), .groups = "drop")
  # and for country-level quantities, whose RANKING is what the project reports
  rank_cty = cmp %>% filter(grepl(":logit_S0", parameter)) %>% group_by(rep) %>%
    summarise(spearman = suppressWarnings(cor(truth, estimate, method = "spearman")), .groups = "drop")
  list(by_family = as.data.frame(by_fam), rank_shared = as.data.frame(rank_rec),
       rank_S0_spearman = median(rank_cty$spearman, na.rm = TRUE), comparison = cmp)
}

# ---- |-the learning-layer recovery: is a known driver effect recovered end to end? ----
# For each replicate the truth had season parameters generated by the covariate x with slopes
# beta_R0 and beta_delta. Here we run the SECOND step of the two-step procedure on the FITTED season
# parameters and see whether those slopes come back.
jm_driver_recovery = function(rec, d){
  rows = lapply(rec$reps, function(r){
    dr = r$driver; if (is.null(dr)) return(NULL)
    c1 = r$comparison %>% filter(grepl("^log_R0", parameter))
    c2 = r$comparison %>% filter(grepl("^delta_", parameter))
    # the constrained season deviation: the last one is minus the sum of the others
    dev_est = c(c2$est_theta, -sum(c2$est_theta)); dev_true = c(c2$truth_theta, -sum(c2$truth_theta))
    b_R0 = coef(lm(c1$est_theta ~ dr$x))[2]
    b_dev = coef(lm(dev_est ~ dr$x))[2]
    data.frame(beta_R0_true = dr$beta_R0, beta_R0_est = unname(b_R0),
               beta_delta_true = dr$beta_delta, beta_delta_est = unname(b_dev))
  })
  out = do.call(rbind, Filter(Negate(is.null), rows))
  if (is.null(out)) return(NULL)
  list(per_rep = out, summary = data.frame(
    quantity = c("beta_R0", "beta_delta"),
    truth = c(out$beta_R0_true[1], out$beta_delta_true[1]),
    mean_estimate = c(mean(out$beta_R0_est), mean(out$beta_delta_est)),
    sd_estimate = c(sd(out$beta_R0_est), sd(out$beta_delta_est)),
    n_rep = nrow(out)))
}
