# joint_recovery.R -- CAN THE FIT RECOVER A KNOWN TRUTH? and the uncertainty machinery it needs.
#
# Architecture, and why it is built this way.
#
# The generative model and the fitted model are THE SAME CODE. Expected counts come from
# jm_fitted_cpp, the identical C++ that the likelihood uses, and the only thing added is the
# negative-binomial draw. So there is no second simulator that can drift away from the model, which is
# the usual way a recovery test ends up testing nothing.
#
# Truth is simulated onto the REAL DESIGN: the same countries, seasons, observed weeks, missing cells,
# populations, contact matrices, vaccination coverages and data sources as the actual panel. The
# question is therefore not "can this model be recovered from ideal data" but "can it be recovered
# from the data we actually have", which is the only question worth asking.
#
# Truth itself comes from a pluggable constructor, and that is the hook for the learning layer:
#   jm_truth_from_fit()    truth = the fitted optimum, optionally jittered. Asks whether the optimum
#                          is locally recoverable and whether the intervals cover.
#   jm_truth_from_prior()  truth drawn from the priors. Asks whether recovery holds across the whole
#                          plausible parameter space, not just near one point.
#   jm_truth_with_driver() truth in which the season parameters are GENERATED BY A DRIVER
#                          (subtype, vaccine effectiveness, prior-season burden). This is the
#                          learning layer's own recovery test: simulate a world where a driver really
#                          does move season transmissibility or season visibility by a known amount,
#                          run the whole two-step pipeline, and check the driver effect comes back.
#                          Without this, a driver association found in real data cannot be told apart
#                          from one manufactured by the fitting procedure.
#
# Everything returns tidy truth-versus-estimate tables, so bias, root-mean-square error, rank
# recovery and interval coverage are all computed the same way whatever the truth constructor was.
#
# AND THE TEST MUST BE ABLE TO FAIL. Every truth constructor above lives inside the model's own
# parameter space, so on its own the harness can only ask "is the optimum findable" -- it would
# certify the model no matter how wrong the model's assumptions are about the world. So there is a
# fourth entry point, jm_simulate_violation(), which simulates from truths the model CANNOT represent,
# and jm_misspecification_check(), which scores the control and the violations side by side. It earns
# its place: `r0_by_country` takes the susceptibility ranking from Spearman 0.97 to 0.09.

suppressMessages({library(dplyr); library(tidyr)})

# ---- |-the transform each slot lives behind ----
# ONE definition, used by the intervals, the profiles and the recovery comparison. It depends only on
# the parameter's NAME, never on the Hessian, which is what lets a recovery replicate skip the
# expensive curvature computation when it does not need intervals. Every transform is monotone, so
# pushing interval endpoints through it is exact for quantiles.
jm_par_kind = function(nm)
  ifelse(grepl("^log_R0", nm), "exp",
  ifelse(grepl("^delta_", nm), "identity",
  ifelse(grepl("^log2_sigma", nm), "pow2",
  ifelse(grepl(":logit_S0", nm), "plogis",
  ifelse(grepl(":off_", nm), "pow2", "exp")))))
jm_par_tr = function(x, kind)
  ifelse(kind == "exp", exp(x),
  ifelse(kind == "plogis", plogis(x),
  ifelse(kind == "pow2", 2^x, x)))

# ---- |-uncertainty: curvature intervals for every parameter ----
# The penalised Hessian at the optimum gives a Gaussian approximation to the posterior on the
# unconstrained scale. Intervals are formed there and then pushed through the parameter's own
# transform, which is exact for quantiles because every transform used here is monotone.
jm_intervals = function(fit, H_post = NULL, level = 0.95){
  d = fit$d; th = fit$theta; nm = names(th)
  if (is.null(H_post)) H_post = optimHess(th, function(x) jm_negll_cpp(x, d))
  H_post = (H_post + t(H_post)) / 2
  V = tryCatch(solve(H_post), error = function(e) NULL)
  se = if (is.null(V)) rep(NA_real_, length(th)) else sqrt(pmax(diag(V), 0))
  z = qnorm(1 - (1 - level) / 2)
  lo_u = th - z * se; hi_u = th + z * se
  kind = jm_par_kind(nm)
  out = data.frame(parameter = nm, kind = kind, theta = unname(th), se = unname(se),
             estimate = jm_par_tr(unname(th), kind), lower = jm_par_tr(unname(lo_u), kind),
             upper = jm_par_tr(unname(hi_u), kind),
             row.names = NULL, stringsAsFactors = FALSE)
  # The LAST season deviation is not a free parameter: it is minus the sum of the others, so the
  # sum-to-zero constraint holds. Its interval needs the delta method, i.e. the variance of that sum,
  # which is the total of the whole covariance sub-block rather than a single diagonal entry.
  S = d$n_season; jf = S + seq_len(S - 1)
  if (!is.null(V)){
    se_last = sqrt(max(sum(V[jf, jf, drop = FALSE]), 0))
    th_last = -sum(th[jf])
    out = rbind(out, data.frame(parameter = paste0("delta_", d$seasons[S]), kind = "identity",
                                theta = th_last, se = se_last, estimate = th_last,
                                lower = th_last - z * se_last, upper = th_last + z * se_last,
                                row.names = NULL, stringsAsFactors = FALSE))
  }
  out
}

# ---- |-uncertainty: profile likelihood for the shared parameters ----
# Curvature intervals assume the objective is a quadratic bowl. Near a flat or banana-shaped valley
# that is exactly what fails, and flat valleys are what this project keeps finding. A profile makes
# no such assumption: fix one parameter on a grid, re-optimise everything else, and read off where the
# objective has risen by qchisq(.95, 1)/2 = 1.92. Only the shared parameters get this treatment --
# they are the ones that will be published, and they are few.
jm_profile = function(fit, idx = NULL, n_grid = 7L, span = 3, sweeps = 2L,
                      cores = max(1L, parallel::detectCores() - 1L), verbose = TRUE){
  d = fit$d; th0 = fit$theta; nm = names(th0)
  if (is.null(idx)) idx = seq_len(2L * d$n_season)              # the shared block by default
  iv = jm_intervals(fit)
  best = fit$negll
  cut = qchisq(0.95, 1) / 2
  bl = jm_blocks(d)
  one = function(j){
    se = iv$se[j]; if (!is.finite(se) || se <= 0) se = 0.1
    grid = th0[j] + seq(-span, span, length.out = n_grid) * se
    vals = vapply(grid, function(g){
      th = th0; th[j] = g
      for (sw in seq_len(sweeps)){
        # every local block, with the shared block (including the fixed j) held
        for (ic in seq_len(d$n_country)){
          ii = bl$local[[ic]]
          f = function(x){ t2 = th; t2[ii] = x; jm_country_negll_cpp(t2, d, ic - 1L) }
          o = tryCatch(optim(th[ii], f, method = "BFGS", control = list(maxit = 200, reltol = 1e-9)),
                       error = function(e) NULL)
          if (!is.null(o)) th[ii] = o$par
        }
        # the rest of the shared block, with j still fixed
        ii = setdiff(bl$shared, j)
        f = function(x){ t2 = th; t2[ii] = x; jm_negll_cpp(t2, d) }
        o = tryCatch(optim(th[ii], f, method = "BFGS", control = list(maxit = 200, reltol = 1e-9)),
                     error = function(e) NULL)
        if (!is.null(o)) th[ii] = o$par
      }
      jm_negll_cpp(th, d)
    }, numeric(1))
    data.frame(parameter = nm[j], j = j, theta = grid, negll = vals, delta = vals - best,
               row.names = NULL, stringsAsFactors = FALSE)
  }
  if (verbose) cat(sprintf("profiling %d parameters on %d grid points...\n", length(idx), n_grid))
  prof = do.call(rbind, parallel::mclapply(idx, one, mc.cores = min(cores, length(idx))))
  # read the interval off each profile by linear interpolation on the two sides of the minimum
  lim = do.call(rbind, lapply(split(prof, prof$parameter), function(p){
    p = p[order(p$theta), ]; imin = which.min(p$delta)
    side = function(seq_i){
      s = p[seq_i, ]; if (nrow(s) < 2) return(NA_real_)
      k = which(s$delta >= cut)[1]
      if (is.na(k) || k == 1) return(NA_real_)
      x1 = s$theta[k - 1]; x2 = s$theta[k]; y1 = s$delta[k - 1]; y2 = s$delta[k]
      x1 + (cut - y1) * (x2 - x1) / (y2 - y1)
    }
    data.frame(parameter = p$parameter[1], j = p$j[1],
               lo_theta = side(rev(seq_len(imin))), hi_theta = side(seq(imin, nrow(p))),
               row.names = NULL, stringsAsFactors = FALSE)
  }))
  lim$kind = iv$kind[lim$j]
  lim$estimate = jm_par_tr(th0[lim$j], lim$kind)
  lim$lower = jm_par_tr(lim$lo_theta, lim$kind); lim$upper = jm_par_tr(lim$hi_theta, lim$kind)
  list(profile = prof, limits = lim, cut = cut)
}

# ============================ the recovery harness ============================

# ---- |-truth constructors. Each returns a full parameter vector on the model's own scale. ----
jm_truth_from_fit = function(fit, jitter_sd = 0){
  th = fit$theta
  if (jitter_sd > 0) th = th + rnorm(length(th), 0, jitter_sd)
  th
}
jm_truth_from_prior = function(d, set = jm_settings(), anchor = NULL){
  # draw from the priors, but keep the seeds near the data-driven start: a seed drawn from its very
  # wide prior would put the wave outside the observation window and test nothing.
  th = if (is.null(anchor)) jm_theta0(d, set) else anchor
  S = d$n_season
  th[seq_len(S)] = rnorm(S, set$pr_R0_mean, set$pr_R0_sd)
  dev = rnorm(S, 0, set$pr_delta_sd); dev = dev - mean(dev)          # respect the sum-to-zero constraint
  th[S + seq_len(S - 1)] = dev[seq_len(S - 1)]
  th[2L * S] = rnorm(1, set$pr_sigma_mean, set$pr_sigma_sd)
  for (ic in seq_len(d$n_country)){
    b = d$off_country[ic]
    th[b + 1] = rnorm(1, set$pr_S0_mean, set$pr_S0_sd)
    th[b + 2] = th[b + 2] + rnorm(1, 0, 0.3)                          # around the data-driven level
    th[b + 3] = rnorm(1, 0, set$pr_off_sd); th[b + 4] = rnorm(1, 0, set$pr_off_sd)
    th[b + 5] = rnorm(1, set$pr_phi_mean, 0.4)
    th[b + 5 + seq_len(d$n_src[ic])] = th[b + 5 + seq_len(d$n_src[ic])] + rnorm(d$n_src[ic], 0, 0.3)
    is = b + 5 + d$n_src[ic] + seq_len(d$n_cs_of_country[ic])
    th[is] = th[is] + rnorm(length(is), 0, 0.5)                       # jitter the arrival, do not redraw it
  }
  names(th) = jm_par_names(d); th
}
# THE LEARNING-LAYER HOOK. x is one covariate value per season (subtype, vaccine effectiveness,
# prior-season burden, ...). The truth is built so that the covariate REALLY DOES move the season
# parameter by a known amount, on the model's own scale:
#   log R0_s     = pr_R0_mean   + beta_R0  * x_s + noise
#   delta_s      = beta_delta * x_s + noise, then centred to average zero
# Running the pipeline on this and regressing the FITTED season parameters back on x recovers
# beta_R0 and beta_delta if and only if the two-step procedure is trustworthy.
jm_truth_with_driver = function(d, x, beta_R0 = 0, beta_delta = 0, set = jm_settings(),
                                noise_R0 = 0.03, noise_delta = 0.15, anchor = NULL){
  stopifnot(length(x) == d$n_season)
  th = if (is.null(anchor)) jm_theta0(d, set) else anchor
  S = d$n_season; xs = as.numeric(scale(x))
  th[seq_len(S)] = set$pr_R0_mean + beta_R0 * xs + rnorm(S, 0, noise_R0)
  dev = beta_delta * xs + rnorm(S, 0, noise_delta); dev = dev - mean(dev)
  th[S + seq_len(S - 1)] = dev[seq_len(S - 1)]
  names(th) = jm_par_names(d)
  attr(th, "driver") = list(x = xs, beta_R0 = beta_R0, beta_delta = beta_delta)
  th
}

# ---- |-simulate one data set from a truth, onto the real design ----
# The expected counts come from the same C++ used by the likelihood; only the negative-binomial draw
# is added. The missing-cell pattern of the real panel is preserved, and the derived fields the
# starting values are built from are recomputed, so the refit starts from the SIMULATED data and gets
# no help from the real series.
jm_simulate = function(theta, d, seed = NULL){
  if (!is.null(seed)) set.seed(seed)
  p = jm_unpack(theta, d); f = jm_fitted_cpp(theta, d)
  ds = d
  for (i in seq_len(d$n_cs)){
    ic = d$cs_country[i] + 1L; phi = p$country[[ic]]$phi
    mu = f$mu[[i]]; ok = is.finite(d$y[[i]])
    ysim = matrix(NA_real_, nrow(mu), ncol(mu))
    ysim[ok] = rnbinom(sum(ok), size = phi, mu = mu[ok])
    dimnames(ysim) = dimnames(d$y[[i]])                              # keep the real design's labels
    ds$y[[i]] = ysim
    ds$lgamma_y1[i] = sum(lgamma(ysim[is.finite(ysim)] + 1))
    ds$rates[[i]] = sweep(ysim, 2, d$rate_per / d$N[[ic]], "*")       # the start is built from these
  }
  ds
}

# ---- |-simulate from a truth the model CANNOT represent ----
# A recovery test that cannot fail is worse than none, because it certifies whatever it is pointed at.
# The truth constructors above all live inside the model's own parameter space, so they can only ever
# ask "is the optimum findable". These VIOLATIONS leave that space deliberately, and the harness has
# to report worse recovery on them. Measured 2026-09-14: `r0_by_country` takes the susceptibility
# ranking from Spearman 0.97 to 0.09, so the test is not vacuous.
#
# The trap to avoid: a "violation" the model absorbs. The first attempt multiplied each country's
# expected counts by a constant, which is EXACTLY what the per-country reporting level c does, so the
# model reproduced it perfectly and the arm tested nothing. A violation must break something no
# parameter can mop up -- `jm_violation_is_real` checks that, and the test suite enforces it.
#
#   r0_by_country  each country gets its own transmissibility multiplier. This is the assumption the
#                  whole design rests on (sharing R0_s across countries is what makes S0_c
#                  identifiable), and R0 changes the wave's SHAPE, so no reporting parameter can
#                  absorb it. sd_log_r0 = 0.10 means countries spanning roughly 0.84-1.20.
#   second_wave    a Gaussian bump late in the season. A single-wave SIR cannot make two humps at any
#                  parameter value. Applied identically to every season, so it degrades FIT without
#                  biasing the between-season contrasts -- which is itself worth knowing.
jm_simulate_violation = function(theta, d, violation = c("none", "r0_by_country", "second_wave"),
                                 seed = NULL, sd_log_r0 = 0.10, bump_height = 0.6,
                                 bump_at = 0.78, bump_width = 3){
  violation = match.arg(violation)
  if (!is.null(seed)) set.seed(seed)
  p = jm_unpack(theta, d); ds = d
  rmul = if (violation == "r0_by_country") exp(rnorm(d$n_country, 0, sd_log_r0)) else rep(1, d$n_country)
  # a per-country R0 has to enter the DYNAMICS, so the model is re-run per country with that country's
  # shared R0 block shifted -- not patched onto mu afterwards, which would be a reporting effect
  mu_all = vector("list", d$n_cs)
  if (violation == "r0_by_country"){
    for (ic in seq_len(d$n_country)){
      th2 = theta; th2[seq_len(d$n_season)] = theta[seq_len(d$n_season)] + log(rmul[ic])
      f2 = jm_fitted_cpp(th2, d)
      for (i in (d$cs_of_country[[ic]] + 1L)) mu_all[[i]] = f2$mu[[i]]
    }
  } else mu_all = jm_fitted_cpp(theta, d)$mu
  mu_base = jm_fitted_cpp(theta, d)$mu
  for (i in seq_len(d$n_cs)){
    ic = d$cs_country[i] + 1L; phi = p$country[[ic]]$phi; mu = mu_all[[i]]
    if (violation == "second_wave"){
      nw = nrow(mu)
      b = bump_height * exp(-((seq_len(nw) - round(bump_at * nw))^2) / (2 * bump_width^2))
      mu = mu * (1 + matrix(b, nw, ncol(mu)))
    }
    mu_all[[i]] = mu
    ok = is.finite(d$y[[i]]); ysim = matrix(NA_real_, nrow(mu), ncol(mu))
    ysim[ok] = rnbinom(sum(ok), size = phi, mu = mu[ok])
    dimnames(ysim) = dimnames(d$y[[i]])
    ds$y[[i]] = ysim; ds$lgamma_y1[i] = sum(lgamma(ysim[is.finite(ysim)] + 1))
    ds$rates[[i]] = sweep(ysim, 2, d$rate_per / d$N[[ic]], "*")
  }
  attr(ds, "violation") = violation; attr(ds, "r0_mult") = rmul
  attr(ds, "mu_ratio") = lapply(seq_len(d$n_cs), function(i) mu_all[[i]] / mu_base[[i]])
  ds
}

# Is the violation REAL, or is it something the model can reparameterise away? A violation that only
# rescales a country's expected counts by a constant is absorbed exactly by that country's reporting
# level, so the ratio to the unperturbed mean has to VARY WITHIN a country-season to count.
jm_violation_is_real = function(ds){
  r = attr(ds, "mu_ratio")
  if (is.null(r)) stop("not a violated data set: build it with jm_simulate_violation()")
  if (identical(attr(ds, "violation"), "none")) return(FALSE)
  # the spread of the ratio within each country-season: zero means a pure per-country rescaling
  within = vapply(r, function(m){ v = m[is.finite(m)]; if (!length(v)) 0 else diff(range(v)) }, numeric(1))
  max(within) > 1e-8
}

# ---- |-one replicate: simulate, refit from scratch, compare with the truth ----
# simulate_fn is the hook that lets a MISSPECIFIED replicate reuse this whole path: pass
# function(theta, d, seed) jm_simulate_violation(theta, d, "r0_by_country", seed) and everything
# downstream -- the comparison table, the family summaries, the rank recovery -- is computed the same
# way, so a violated arm is directly comparable with the control rather than scored by separate code.
jm_recover_once = function(d, theta_true, seed, fit_args = list(), with_intervals = TRUE,
                           simulate_fn = jm_simulate, verbose = FALSE){
  ds = simulate_fn(theta_true, d, seed)
  fit = do.call(jm_fit, c(list(d = ds, theta0 = jm_theta0(ds), verbose = verbose), fit_args))
  nm = jm_par_names(d)
  kind = jm_par_kind(nm)
  out = data.frame(parameter = nm, seed = seed,
                   truth_theta = unname(theta_true), est_theta = unname(fit$theta),
                   truth = jm_par_tr(unname(theta_true), kind),
                   estimate = jm_par_tr(unname(fit$theta), kind),
                   row.names = NULL, stringsAsFactors = FALSE)
  # The Hessian is the expensive part of a replicate (minutes, against ~100 s for the fit itself), and
  # the transform above needs only the NAMES, so it is computed ONLY when intervals are asked for.
  if (with_intervals){
    iv = jm_intervals(fit)
    # jm_intervals returns one row per FREE parameter plus one derived row for the constrained season
    # deviation, so it must be matched BY NAME rather than by position -- assuming equal lengths is how
    # this silently broke once already.
    ivm = iv[match(nm, iv$parameter), ]
    stopifnot(!anyNA(ivm$kind), identical(ivm$kind, kind))
    out$lower = ivm$lower; out$upper = ivm$upper
    out$covered = out$truth >= pmin(ivm$lower, ivm$upper) & out$truth <= pmax(ivm$lower, ivm$upper)
  }
  list(comparison = out, negll = fit$negll, loglik = fit$loglik, seconds = fit$seconds,
       conv = c(fit$conv_local, fit$conv_shared, fit$conv_polish), theta = fit$theta,
       violation = attr(ds, "violation"), adequacy_excess = median(jm_adequacy(fit)$excess, na.rm = TRUE))
}

# ---- |-many replicates ----
# Replicates run SEQUENTIALLY because each fit already parallelises over countries; nesting the two
# would oversubscribe the cores and be slower, not faster.
jm_recovery = function(d, truth_fn = function(i) jm_truth_from_fit(fit0), n_rep = 10L, seed0 = 1000L,
                       fit_args = list(), verbose = TRUE){
  reps = vector("list", n_rep); t0 = Sys.time()
  for (i in seq_len(n_rep)){
    set.seed(seed0 + i)
    tt = truth_fn(i)
    r = tryCatch(jm_recover_once(d, tt, seed0 + i, fit_args), error = function(e){ cat("  rep", i, "FAILED:", conditionMessage(e), "\n"); NULL })
    if (!is.null(r)){ r$comparison$rep = i; r$driver = attr(tt, "driver"); reps[[i]] = r }
    if (verbose) cat(sprintf("  rep %2d/%d: negll %.1f, %.0f s (elapsed %.1f min)\n", i, n_rep,
                             if (is.null(r)) NA else r$negll, if (is.null(r)) NA else r$seconds,
                             as.numeric(difftime(Sys.time(), t0, units = "mins"))))
  }
  reps = Filter(Negate(is.null), reps)
  list(reps = reps, comparison = do.call(rbind, lapply(reps, `[[`, "comparison")),
       minutes = as.numeric(difftime(Sys.time(), t0, units = "mins")))
}

# ---- |-what the replicates say: bias, error, rank recovery, coverage ----
jm_recovery_summary = function(rec, d){
  cmp = rec$comparison
  fam = function(nm) ifelse(grepl("^log_R0", nm), "R0 (season, shared)",
        ifelse(grepl("^delta_", nm), "season deviation (shared)",
        ifelse(grepl("^log2_sigma", nm), "elderly susceptibility (global)",
        ifelse(grepl(":logit_S0", nm), "S0 (country)",
        ifelse(grepl(":log_c$", nm), "reporting c (country)",
        ifelse(grepl(":off_", nm), "age reporting offset",
        ifelse(grepl(":log_phi", nm), "dispersion phi",
        ifelse(grepl(":log_b_", nm), "baseline b", "seed I0 (country-season)"))))))))
  cmp$family = fam(cmp$parameter)
  by_fam = cmp %>% group_by(family) %>%
    summarise(n = n(),
              bias_theta = mean(est_theta - truth_theta),
              rmse_theta = sqrt(mean((est_theta - truth_theta)^2)),
              rel_bias = mean((estimate - truth) / abs(truth)),
              coverage = if ("covered" %in% names(cmp)) mean(covered, na.rm = TRUE) else NA_real_,
              .groups = "drop") %>% arrange(family)
  # rank recovery: within each replicate, does the ORDER of the shared season parameters come back?
  rank_rec = cmp %>% filter(grepl("^log_R0|^delta_", parameter)) %>%
    mutate(block = ifelse(grepl("^log_R0", parameter), "R0 by season", "season deviation")) %>%
    group_by(rep, block) %>%
    summarise(spearman = suppressWarnings(cor(truth, estimate, method = "spearman")),
              pearson = cor(truth, estimate), .groups = "drop") %>%
    group_by(block) %>% summarise(spearman_med = median(spearman, na.rm = TRUE),
                                  pearson_med = median(pearson, na.rm = TRUE), n_rep = n(), .groups = "drop")
  # and for country-level quantities, whose RANKING is what the project reports
  rank_cty = cmp %>% filter(grepl(":logit_S0", parameter)) %>% group_by(rep) %>%
    summarise(spearman = suppressWarnings(cor(truth, estimate, method = "spearman")), .groups = "drop")
  list(by_family = as.data.frame(by_fam), rank_shared = as.data.frame(rank_rec),
       rank_S0_spearman = median(rank_cty$spearman, na.rm = TRUE), comparison = cmp)
}

# ---- |-CAN THE RECOVERY TEST FAIL? the misspecification arms ----
# Run the control and each violation on the same truth and the same seed, and report the recovery
# scores side by side. The control says what good looks like on this design; a violation that scores
# the same as the control means the harness is blind to it, which is a finding about the DIAGNOSTIC,
# not a reassurance about the model.
#
# Measured on the real 12-country design, 2026-09-14 (one replicate per arm, seed 601):
#   arm                 R0 rank   visibility rank   S0 rank   noise excess
#   control (truth representable)  1.00      0.96        0.97        1.25x
#   r0_by_country (sd log 0.10)    0.95      0.96        0.09        1.26x
#   second_wave (+60% late bump)   0.93      0.96        0.99        1.24x
# Read: the season-level conclusions survive both violations; the susceptibility RANKING collapses
# when R0 sharing is false, because sharing R0 is exactly what identifies S0, so a country's true R0
# deviation has nowhere to go but into its S0. And the noise budget cannot see either violation, so it
# is not the diagnostic for this failure -- a per-country R0 multiplier fitted as an ALTERNATIVE MODEL
# and compared by likelihood is (the learning layer's first job).
jm_misspecification_check = function(d, theta_true, violations = c("r0_by_country", "second_wave"),
                                     seed = 601L, fit_args = list(), sd_log_r0 = 0.10,
                                     verbose = TRUE){
  arms = c("none", violations)
  rows = lapply(arms, function(v){
    sim = function(theta, dd, s) jm_simulate_violation(theta, dd, v, seed = s, sd_log_r0 = sd_log_r0)
    if (verbose) cat(sprintf("  arm %-14s ", v))
    t0 = Sys.time()
    r = jm_recover_once(d, theta_true, seed, fit_args = fit_args, with_intervals = FALSE,
                        simulate_fn = sim)
    cmp = r$comparison
    rk = function(pat, method = "spearman"){
      s = cmp[grepl(pat, cmp$parameter), ]
      if (nrow(s) < 3) return(NA_real_)
      suppressWarnings(cor(s$truth, s$estimate, method = method))
    }
    out = data.frame(arm = v, absorbable = if (v == "none") NA
                       else !jm_violation_is_real(sim(theta_true, d, seed)),
                     rank_R0 = rk("^log_R0"), rank_visibility = rk("^delta_"),
                     rank_S0 = rk(":logit_S0"), rank_c = rk(":log_c"),
                     noise_excess = r$adequacy_excess, negll = r$negll,
                     seconds = as.numeric(difftime(Sys.time(), t0, units = "secs")),
                     row.names = NULL)
    if (verbose) cat(sprintf("R0 %.2f  visibility %.2f  S0 %.2f  noise %.2fx  [%.0f s]\n",
                             out$rank_R0, out$rank_visibility, out$rank_S0, out$noise_excess,
                             out$seconds))
    out
  })
  out = do.call(rbind, rows)
  ctl = out[out$arm == "none", ]
  # a violation is DETECTED if it degrades any reported ranking materially; the noise excess is
  # reported alongside so its blindness is on the record rather than assumed
  out$detected_by_ranking = out$arm != "none" &
    (out$rank_R0 < ctl$rank_R0 - 0.15 | out$rank_visibility < ctl$rank_visibility - 0.15 |
     out$rank_S0 < ctl$rank_S0 - 0.15)
  out$detected_by_noise = out$arm != "none" & out$noise_excess > ctl$noise_excess * 1.25
  out
}

# ---- |-the learning-layer recovery: is a known driver effect recovered end to end? ----
# For each replicate the truth had season parameters generated by the covariate x with slopes
# beta_R0 and beta_delta. Here we run the SECOND step of the two-step procedure on the FITTED season
# parameters and see whether those slopes come back.
jm_driver_recovery = function(rec, d){
  rows = lapply(rec$reps, function(r){
    dr = r$driver; if (is.null(dr)) return(NULL)
    c1 = r$comparison %>% filter(grepl("^log_R0", parameter))
    c2 = r$comparison %>% filter(grepl("^delta_", parameter))
    # the constrained season deviation: the last one is minus the sum of the others
    dev_est = c(c2$est_theta, -sum(c2$est_theta)); dev_true = c(c2$truth_theta, -sum(c2$truth_theta))
    b_R0 = coef(lm(c1$est_theta ~ dr$x))[2]
    b_dev = coef(lm(dev_est ~ dr$x))[2]
    data.frame(beta_R0_true = dr$beta_R0, beta_R0_est = unname(b_R0),
               beta_delta_true = dr$beta_delta, beta_delta_est = unname(b_dev))
  })
  out = do.call(rbind, Filter(Negate(is.null), rows))
  if (is.null(out)) return(NULL)
  list(per_rep = out, summary = data.frame(
    quantity = c("beta_R0", "beta_delta"),
    truth = c(out$beta_R0_true[1], out$beta_delta_true[1]),
    mean_estimate = c(mean(out$beta_R0_est), mean(out$beta_delta_est)),
    sd_estimate = c(sd(out$beta_R0_est), sd(out$beta_delta_est)),
    n_rep = nrow(out)))
}
